// Vous devez complétéer ce fichier
@startuml

skinparam style strictuml
skinparam sequenceMessageAlign center
scale 1

title "RDCU pour redémarrerJeu"

participant ":JeuDeDes" as JeuDeDes
participant "joueurs:Map<String,Joueur>" as joueurs



-> JeuDeDes : redemarrerJeu()
note right of JeuDeDes
 selon Contrôleur
 (JeuDeDés est
 l'objet racine)
end note

JeuDeDes -> joueurs :clear()
note right of joueurs
 selon Expert
end note

@enduml